/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.ChiPhiBUS;
import BUS.ChiTietDoanBUS;
import BUS.DoanBUS;
import BUS.KhachBUS;
import BUS.LoaiChiPhiBUS;
import BUS.NhanVienBUS;
import BUS.NhanVienTrongDoanBUS;
import DTO.ChiPhi;
import DTO.ChiTietDoan;
import DTO.NhanVienTrongDoan;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xenov
 */
public class ChinhSuaDoan extends javax.swing.JFrame {
    
    DefaultTableModel tableChiPhi;
    DefaultTableModel tableNhanVienTrongDoan;
    DefaultTableModel tableChiTietDoan;
    
    private ArrayList<DTO.ChiPhi> arrayChiPhi;
    private ArrayList<DTO.NhanVienTrongDoan> arrayNhanVienTrongDoan;
    private ArrayList<DTO.ChiTietDoan> arrayChiTietDoan;
    /**
     * Creates new form ChinhSuaDoan
     */
    public ChinhSuaDoan( int madoan) {
        initComponents();
        setLocationRelativeTo(null);
        hienThiDuLieuDoan(madoan);
        loadArrayLists(madoan);
        hienThiDuLieuLenBangChiPhi(madoan);
        hienThiDuLieuLenBangNhanVien(madoan);
        hienThiDuLieuLenBangKhach(madoan);
        setComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaDoan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaTour = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdcNgayBD = new com.toedter.calendar.JDateChooser();
        jdcNgayKT = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbLoaiChiPhi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtGiatien = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtChiPhi = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbNhiemVu = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtNhanVienTrongDoan = new javax.swing.JTable();
        cbMaNhanVien = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbMaKhach = new javax.swing.JComboBox<>();
        txtTenKhach = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtChiTietDoan = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("QUẢN LÝ ĐOÀN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        jLabel2.setText("Mã đoàn");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        txtMaDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDoanActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaDoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 80, -1));

        jLabel3.setText("Mã tour");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, 20));
        getContentPane().add(txtMaTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 80, -1));

        jLabel4.setText("Ngày bắt đầu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, 20));

        jLabel5.setText("Ngày kết thúc");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, 20));
        getContentPane().add(jdcNgayBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 134, -1));
        getContentPane().add(jdcNgayKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 132, -1));

        jButton1.setText("Lưu");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 290, -1));

        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 90, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi phí"));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setText("Loại chi phí");

        cbLoaiChiPhi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Giá tiền");

        jButton3.setText("Thêm");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Sửa");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Xóa");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jtChiPhi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Loại chi phí", "Giá tiền"
            }
        ));
        jtChiPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtChiPhiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtChiPhi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbLoaiChiPhi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGiatien)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbLoaiChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiatien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 460));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhân viên"));

        jLabel8.setText("Mã nhân viên");

        jLabel9.setText("Nhiệm vụ");

        cbNhiemVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tài xế", "Hướng dẫn viên", "Thuyết trình", "Bảo kê", "Bảo An", "Ông chủ", "Con ông chủ", "Khác" }));

        jLabel10.setText("Họ tên");

        txtHoTen.setEnabled(false);

        jButton6.setText("Thêm");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Sửa");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Xóa");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jtNhanVienTrongDoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Nhiệm vụ"
            }
        ));
        jtNhanVienTrongDoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtNhanVienTrongDoanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtNhanVienTrongDoan);

        cbMaNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMaNhanVien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMaNhanVienItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addComponent(cbNhiemVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoTen)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbNhiemVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, 460));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Khách"));

        jLabel11.setText("Mã khách");

        jLabel12.setText("Tên khách");

        cbMaKhach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMaKhach.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMaKhachItemStateChanged(evt);
            }
        });
        cbMaKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaKhachActionPerformed(evt);
            }
        });

        txtTenKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachActionPerformed(evt);
            }
        });

        jLabel13.setText("CMND");

        jButton9.setText("Thêm");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setText("Sửa");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setText("Xóa");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jtChiTietDoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã khách", "Tên khách", "CMND"
            }
        ));
        jtChiTietDoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtChiTietDoanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtChiTietDoan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(cbMaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtCMND))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbMaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, -1, 460));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1280, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            // TODO add your handling code here:
            // Luu doan
            DoanBUS bus = new DoanBUS();
            bus.docDuLieu();
            int result = JOptionPane.showConfirmDialog(null, "Xác nhận sửa ?","Xác nhận",JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                //luu doan
                DTO.Doan gt = new DTO.Doan();
                gt.setMadoan(Integer.parseInt(txtMaDoan.getText()));
                gt.setMatour(Integer.parseInt(txtMaTour.getText()));
                gt.setNbd(jdcNgayBD.getDate());
                gt.setNkt(jdcNgayKT.getDate());
                int check = bus.sua(gt);
                
                //luu chi phi
                ChiPhiBUS cpbus = new ChiPhiBUS();
                bus.docDuLieu();
                cpbus.xoaChiPhiCoMaDoan(gt.getMadoan());
                if(arrayChiPhi.size() > 0)
                    check += cpbus.ThemAutoPrimaryKey(arrayChiPhi);
                
                //luu nhanvien
                NhanVienTrongDoanBUS nvtdbus  = new NhanVienTrongDoanBUS();
                nvtdbus.docDuLieu();
                nvtdbus.xoaNhanVienCoMaDoan(Integer.parseInt(txtMaDoan.getText()));
                if(arrayNhanVienTrongDoan.size() > 0)
                    check += nvtdbus.Them(arrayNhanVienTrongDoan);
                
                //luu khach
                ChiTietDoanBUS ctdbus  = new ChiTietDoanBUS();
                ctdbus.docDuLieu();
                ctdbus.xoaKhachCoMaDoan(Integer.parseInt(txtMaDoan.getText()));
                if(arrayChiTietDoan.size() > 0)
                    check += ctdbus.themAutoPrimaryKey(arrayChiTietDoan);
                
                if(check == 4){
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        try {
            // TODO add your handling code here:
            LoaiChiPhiBUS lcpbus = new LoaiChiPhiBUS();
            lcpbus.docDuLieu();
            DTO.ChiPhi cp = new DTO.ChiPhi();
            cp.setMachiphi(0);
            cp.setMadoan(Integer.parseInt(txtMaDoan.getText()));
            System.out.println("MA: ");
            cp.setMaloaichiphi(lcpbus.getMaLoaiChiPhi(cbLoaiChiPhi.getSelectedItem().toString()));
            System.out.println("MA: " + cp.getMaloaichiphi());
            cp.setGiatien(Integer.parseInt(txtGiatien.getText()));
            arrayChiPhi.add(cp);
            Vector vt = new Vector();
            vt.add(cbLoaiChiPhi.getSelectedItem()+"");
            vt.add(txtGiatien.getText());
            tableChiPhi.addRow(vt);
            jtChiPhi.setModel(tableChiPhi);
            
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jtChiPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtChiPhiMouseClicked
        // TODO add your handling code here:
        int i = jtChiPhi.getSelectedRow();
        if(i>=0)
        {
            cbLoaiChiPhi.setSelectedItem(jtChiPhi.getValueAt(i, 0));
            txtGiatien.setText(jtChiPhi.getValueAt(i, 1) +"");
        }
    }//GEN-LAST:event_jtChiPhiMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        int i = jtChiPhi.getSelectedRow();
        if( i>= 0)
        {
            try {
            // TODO add your handling code here:
            LoaiChiPhiBUS lcpbus = new LoaiChiPhiBUS();
            lcpbus.docDuLieu();
            DTO.ChiPhi cp = new DTO.ChiPhi();
            cp.setMachiphi(0);
            cp.setMadoan(Integer.parseInt(txtMaDoan.getText()));
       
            cp.setMaloaichiphi(lcpbus.getMaLoaiChiPhi(cbLoaiChiPhi.getSelectedItem().toString()));
       
            cp.setGiatien(Integer.parseInt(txtGiatien.getText()));
            
            arrayChiPhi.set(i, cp);
            tableChiPhi.setValueAt(cbLoaiChiPhi.getSelectedItem().toString(), i, 0);
            tableChiPhi.setValueAt(txtGiatien.getText(), i, 1);
            jtChiPhi.setModel(tableChiPhi);
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        int i = jtChiPhi.getSelectedRow();
        if( i>= 0)
        {
            try {
            // TODO add your handling code here:
            arrayChiPhi.remove(i);
            tableChiPhi.removeRow(i);
            jtChiPhi.setModel(tableChiPhi);
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jtNhanVienTrongDoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtNhanVienTrongDoanMouseClicked
        // TODO add your handling code here:
        int i = jtNhanVienTrongDoan.getSelectedRow();
        if(i>=0)
        {
            cbMaNhanVien.setSelectedItem(jtNhanVienTrongDoan.getValueAt(i, 0));
            txtHoTen.setText(jtNhanVienTrongDoan.getValueAt(i, 1)+"");
            cbNhiemVu.setSelectedItem(jtNhanVienTrongDoan.getValueAt(i, 2));
        }
    }//GEN-LAST:event_jtNhanVienTrongDoanMouseClicked

    private void cbMaNhanVienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMaNhanVienItemStateChanged
        try {
            // TODO add your handling code here:
            NhanVienBUS nvbus = new NhanVienBUS();
            nvbus.docDuLieu();
            DTO.NhanVien nv = nvbus.getNhanVien(Integer.parseInt(cbMaNhanVien.getSelectedItem()+""));
            txtHoTen.setText(nv.getTennhanvien());
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbMaNhanVienItemStateChanged

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        NhanVienTrongDoan nvtd = new NhanVienTrongDoan();
        nvtd.setMadoan(Integer.parseInt(txtMaDoan.getText()));
        nvtd.setManhanvien(Integer.parseInt(cbMaNhanVien.getSelectedItem()+""));
        nvtd.setNhiemvu(cbNhiemVu.getSelectedItem()+"");
        arrayNhanVienTrongDoan.add(nvtd);
        Vector vt = new Vector();
        vt.add(nvtd.getManhanvien());
        vt.add(txtHoTen.getText());
        vt.add(nvtd.getNhiemvu());
        tableNhanVienTrongDoan.addRow(vt);
        jtNhanVienTrongDoan.setModel(tableNhanVienTrongDoan);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        int i = jtNhanVienTrongDoan.getSelectedRow();
        if(i>=0)
        {
            NhanVienTrongDoan nvtd = new NhanVienTrongDoan();
            nvtd.setMadoan(Integer.parseInt(txtMaDoan.getText()));
            nvtd.setManhanvien(Integer.parseInt(cbMaNhanVien.getSelectedItem()+""));
            nvtd.setNhiemvu(cbNhiemVu.getSelectedItem()+"");
            arrayNhanVienTrongDoan.set(i,nvtd);
          
            tableNhanVienTrongDoan.setValueAt(nvtd.getManhanvien(), i, 0);
            tableNhanVienTrongDoan.setValueAt(txtHoTen.getText(), i, 1);
            tableNhanVienTrongDoan.setValueAt(nvtd.getNhiemvu(), i, 2);
            jtNhanVienTrongDoan.setModel(tableNhanVienTrongDoan);
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        int i = jtNhanVienTrongDoan.getSelectedRow();
        if(i>=0)
        {
            arrayNhanVienTrongDoan.remove(i);
            tableNhanVienTrongDoan.removeRow(i);
            jtNhanVienTrongDoan.setModel(tableNhanVienTrongDoan);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void cbMaKhachItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMaKhachItemStateChanged
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            KhachBUS khbus = new KhachBUS();
            khbus.docDuLieu();
            DTO.Khach kh = khbus.getKhach(Integer.parseInt(cbMaKhach.getSelectedItem()+""));
            txtTenKhach.setText(kh.getTenkhach());
            txtCMND.setText(kh.getCmnd()+"");
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbMaKhachItemStateChanged

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        DTO.ChiTietDoan ctd = new DTO.ChiTietDoan();
        ctd.setMadoan(Integer.parseInt(txtMaDoan.getText()));
        ctd.setMakhach(Integer.parseInt(cbMaKhach.getSelectedItem()+""));
        arrayChiTietDoan.add(ctd);
        
        Vector vt = new Vector();
        vt.add(ctd.getMakhach());
        vt.add(txtTenKhach.getText());
        vt.add(txtCMND.getText());
        tableChiTietDoan.addRow(vt);
        jtChiTietDoan.setModel(tableChiTietDoan);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        int i = jtChiTietDoan.getSelectedRow();
        if(i>=0)
        {
            ChiTietDoan ctd = new ChiTietDoan();
            ctd.setMadoan(Integer.parseInt(txtMaDoan.getText()));
            ctd.setMadoan(Integer.parseInt(txtMaDoan.getText()));
            ctd.setMakhach(Integer.parseInt(cbMaKhach.getSelectedItem()+""));
            arrayChiTietDoan.set(i,ctd);
          
            tableChiTietDoan.setValueAt(ctd.getMakhach(), i, 0);
            tableChiTietDoan.setValueAt(txtTenKhach.getText(), i, 1);
            tableChiTietDoan.setValueAt(txtCMND.getText(), i, 2);
            jtChiTietDoan.setModel(tableChiTietDoan);
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        int i = jtChiTietDoan.getSelectedRow();
        if(i>=0)
        {
            arrayChiTietDoan.remove(i);
            tableChiTietDoan.removeRow(i);
            jtChiTietDoan.setModel(tableChiTietDoan);
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jtChiTietDoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtChiTietDoanMouseClicked
        // TODO add your handling code here:
        int i = jtChiTietDoan.getSelectedRow();
        if(i>=0)
        {
            cbMaKhach.setSelectedItem(jtChiTietDoan.getValueAt(i, 0));
            txtTenKhach.setText(jtChiTietDoan.getValueAt(i, 1)+"");
            txtCMND.setText(jtChiTietDoan.getValueAt(i, 2)+"");
        }
    }//GEN-LAST:event_jtChiTietDoanMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Doan doan = new Doan();
        doan.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTenKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachActionPerformed

    private void cbMaKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaKhachActionPerformed

    private void txtMaDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaDoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaDoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaDoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaDoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChinhSuaDoan(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbLoaiChiPhi;
    private javax.swing.JComboBox<String> cbMaKhach;
    private javax.swing.JComboBox<String> cbMaNhanVien;
    private javax.swing.JComboBox<String> cbNhiemVu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdcNgayBD;
    private com.toedter.calendar.JDateChooser jdcNgayKT;
    private javax.swing.JTable jtChiPhi;
    private javax.swing.JTable jtChiTietDoan;
    private javax.swing.JTable jtNhanVienTrongDoan;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtGiatien;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaDoan;
    private javax.swing.JTextField txtMaTour;
    private javax.swing.JTextField txtTenKhach;
    // End of variables declaration//GEN-END:variables

    private void hienThiDuLieuDoan(int madoan) {
        DoanBUS bus = new DoanBUS();
        try {
            bus.docDuLieu();
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        DTO.Doan doan = bus.getDoan(madoan);
        txtMaDoan.setText(doan.getMadoan()+"");
        txtMaTour.setText(doan.getMatour()+"");
        jdcNgayBD.setDate(doan.getNbd());
        jdcNgayKT.setDate(doan.getNkt());
        
        
    }

    private void hienThiDuLieuLenBangChiPhi(int madoan) {
        
        tableChiPhi = (DefaultTableModel) jtChiPhi.getModel();
        tableChiPhi.setRowCount(0);
        LoaiChiPhiBUS lcpbus = new LoaiChiPhiBUS();
        try {
            lcpbus.docDuLieu();
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(DTO.ChiPhi cp : arrayChiPhi)
        {
            Vector vt = new Vector();
            vt.add(lcpbus.getTenLoaiChiPhi(cp.getMaloaichiphi()));
            vt.add(cp.getGiatien());
            tableChiPhi.addRow(vt);
        }
        jtChiPhi.setModel(tableChiPhi);
        
    }

    private void loadArrayLists(int madoan) {
        ChiPhiBUS cpbus = new ChiPhiBUS();
        try {
            cpbus.docDuLieu();
            arrayChiPhi = cpbus.findMaDoan(madoan);
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        NhanVienTrongDoanBUS nvtdbus = new NhanVienTrongDoanBUS();
        try {
            nvtdbus.docDuLieu();
            arrayNhanVienTrongDoan = nvtdbus.findMaDoan(madoan);
       
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        ChiTietDoanBUS ctdbus = new ChiTietDoanBUS();
        try {
            ctdbus.docDuLieu();
            arrayChiTietDoan = ctdbus.findMaDoan(madoan);
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setComboBoxes() {
        try {
            LoaiChiPhiBUS lcpbus = new LoaiChiPhiBUS();
                lcpbus.docDuLieu();
            Vector vt = new Vector();
            for(DTO.LoaiChiPhi lcp : lcpbus.ds)
            {
                vt.add(lcp.getTenloaichiphi());
            }
            cbLoaiChiPhi.setModel(new DefaultComboBoxModel(vt));
            
            //nhan vien combobox
            NhanVienBUS nvbus = new NhanVienBUS();
            nvbus.docDuLieu();
            vt = new Vector();
            for(DTO.NhanVien nv : nvbus.ds)
            {
                vt.add(nv.getManhanvien());
            }
            cbMaNhanVien.setModel(new DefaultComboBoxModel(vt));
            
            //khach combobox
            KhachBUS kbus = new KhachBUS();
            kbus.docDuLieu();
            vt = new Vector();
            for(DTO.Khach kh : kbus.ds)
            {
                vt.add(kh.getMakhach());
            }
            cbMaKhach.setModel(new DefaultComboBoxModel(vt));
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void hienThiDuLieuLenBangNhanVien(int madoan) {
        
        tableNhanVienTrongDoan = (DefaultTableModel) jtNhanVienTrongDoan.getModel();
        tableNhanVienTrongDoan.setRowCount(0);
        NhanVienTrongDoanBUS nvtdbus = new NhanVienTrongDoanBUS();
        NhanVienBUS nvbus = new NhanVienBUS();
        try {
            nvbus.docDuLieu();
            nvtdbus.docDuLieu();
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(DTO.NhanVienTrongDoan nv : arrayNhanVienTrongDoan)
        {
            Vector vt = new Vector();
            vt.add(nv.getManhanvien());
            vt.add(nvbus.getNhanVien(nv.getManhanvien()).getTennhanvien());
            vt.add(nv.getNhiemvu());
            tableNhanVienTrongDoan.addRow(vt);
        }
        jtNhanVienTrongDoan.setModel(tableNhanVienTrongDoan);
    }

    private void hienThiDuLieuLenBangKhach(int madoan) {
        
        tableChiTietDoan = (DefaultTableModel) jtChiTietDoan.getModel();
        tableChiTietDoan.setRowCount(0);
        ChiTietDoanBUS ctdbus = new ChiTietDoanBUS();
        KhachBUS khbus = new KhachBUS();
        try {
            ctdbus.docDuLieu();
            khbus.docDuLieu();
        } catch (Exception ex) {
            Logger.getLogger(ChinhSuaDoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(DTO.ChiTietDoan ctd : arrayChiTietDoan)
        {
            Vector vt = new Vector();
            vt.add(ctd.getMakhach());
            vt.add(khbus.getKhach(ctd.getMakhach()).getTenkhach());
            vt.add(khbus.getKhach(ctd.getMakhach()).getCmnd());
            tableChiTietDoan.addRow(vt);
        }
        jtChiTietDoan.setModel(tableChiTietDoan);
    }
}
