/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MAIN;

import BLL.NavigationBUS;
import DTO.ListDTO;
import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JPanel;
import GUI.*;
import java.util.ArrayList;

/**
 *
 * @author ADMIN
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        NavigationBUS nav = new NavigationBUS(jPnCon);
        nav.setView(tourjPanel, TourjLabel);
        
        ArrayList<ListDTO> listItem = new ArrayList<>();
        listItem.add (new ListDTO ("Tour", tourjPanel,TourjLabel));
        listItem.add (new ListDTO ("Giá", GiajPanel, GiajLabel));
        listItem.add(new ListDTO("Đoàn",DoanjPanel,DoanjLabel));
        listItem.add(new ListDTO("Chi Phí",CPPanel,CPLabel));
        listItem.add(new ListDTO("Khách hàng",KHjPanel,KHjLabel));
        listItem.add(new ListDTO("Nhân viên",NVjPanel,NVjLabel));
        listItem.add(new ListDTO("Thống kê",TKjPanel5,TKjLabel));
        listItem.add(new ListDTO("Loại Tour",LTjPanel,TKjLabel1));
         listItem.add(new ListDTO("Địa Điểm",DDjPanel,DDjLabell));
        nav.setEvent(listItem);
    }
//  Panel_NhanVien pnNV = new Panel_NhanVien();
//    Panel_KhachHang pnKH = new Panel_KhachHang();
//    Panel_ChiPhi pnCP = new Panel_ChiPhi();
//    Panel_Gia pnGia = new Panel_Gia();
//    Panel_Doan pnDoan = new Panel_Doan();
//    Panel_Tour pnTour = new Panel_Tour();
//    Panel_DiaDiem pnDd = new Panel_DiaDiem();
//    Panel_ThongKe pnTk = new Panel_ThongKe();
   
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        tourjPanel = new javax.swing.JPanel();
        TourjLabel = new javax.swing.JLabel();
        GiajPanel = new javax.swing.JPanel();
        GiajLabel = new javax.swing.JLabel();
        DoanjPanel = new javax.swing.JPanel();
        DoanjLabel = new javax.swing.JLabel();
        KHjPanel = new javax.swing.JPanel();
        KHjLabel = new javax.swing.JLabel();
        CPPanel = new javax.swing.JPanel();
        CPLabel = new javax.swing.JLabel();
        NVjPanel = new javax.swing.JPanel();
        NVjLabel = new javax.swing.JLabel();
        TKjPanel5 = new javax.swing.JPanel();
        TKjLabel = new javax.swing.JLabel();
        LTjPanel = new javax.swing.JPanel();
        TKjLabel1 = new javax.swing.JLabel();
        jPnCon = new javax.swing.JPanel();
        DDjPanel = new javax.swing.JPanel();
        DDjLabell = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 247, 241));

        btnDangXuat.setBackground(new java.awt.Color(131, 51, 233));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        tourjPanel.setBackground(new java.awt.Color(180, 159, 220));

        TourjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TourjLabel.setText("Quản lý Tour");

        javax.swing.GroupLayout tourjPanelLayout = new javax.swing.GroupLayout(tourjPanel);
        tourjPanel.setLayout(tourjPanelLayout);
        tourjPanelLayout.setHorizontalGroup(
            tourjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tourjPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(TourjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tourjPanelLayout.setVerticalGroup(
            tourjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tourjPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(TourjLabel)
                .addGap(19, 19, 19))
        );

        GiajPanel.setBackground(new java.awt.Color(180, 159, 220));

        GiajLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GiajLabel.setText("Quản lý Giá Tour");

        javax.swing.GroupLayout GiajPanelLayout = new javax.swing.GroupLayout(GiajPanel);
        GiajPanel.setLayout(GiajPanelLayout);
        GiajPanelLayout.setHorizontalGroup(
            GiajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GiajPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(GiajLabel)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        GiajPanelLayout.setVerticalGroup(
            GiajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GiajPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GiajLabel)
                .addGap(29, 29, 29))
        );

        DoanjPanel.setBackground(new java.awt.Color(180, 159, 220));

        DoanjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DoanjLabel.setText("Quản lý đoàn");

        javax.swing.GroupLayout DoanjPanelLayout = new javax.swing.GroupLayout(DoanjPanel);
        DoanjPanel.setLayout(DoanjPanelLayout);
        DoanjPanelLayout.setHorizontalGroup(
            DoanjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoanjPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(DoanjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DoanjPanelLayout.setVerticalGroup(
            DoanjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoanjPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(DoanjLabel)
                .addGap(19, 19, 19))
        );

        KHjPanel.setBackground(new java.awt.Color(180, 159, 220));

        KHjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KHjLabel.setText("Quản lý khách hàng");

        javax.swing.GroupLayout KHjPanelLayout = new javax.swing.GroupLayout(KHjPanel);
        KHjPanel.setLayout(KHjPanelLayout);
        KHjPanelLayout.setHorizontalGroup(
            KHjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KHjPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(KHjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        KHjPanelLayout.setVerticalGroup(
            KHjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KHjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KHjLabel)
                .addGap(29, 29, 29))
        );

        CPPanel.setBackground(new java.awt.Color(180, 159, 220));

        CPLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CPLabel.setText("Quản lý chi phí");

        javax.swing.GroupLayout CPPanelLayout = new javax.swing.GroupLayout(CPPanel);
        CPPanel.setLayout(CPPanelLayout);
        CPPanelLayout.setHorizontalGroup(
            CPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(CPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        CPPanelLayout.setVerticalGroup(
            CPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CPPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CPLabel)
                .addGap(29, 29, 29))
        );

        NVjPanel.setBackground(new java.awt.Color(180, 159, 220));

        NVjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NVjLabel.setText("Quản lý nhân viên");

        javax.swing.GroupLayout NVjPanelLayout = new javax.swing.GroupLayout(NVjPanel);
        NVjPanel.setLayout(NVjPanelLayout);
        NVjPanelLayout.setHorizontalGroup(
            NVjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NVjPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(NVjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NVjPanelLayout.setVerticalGroup(
            NVjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NVjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NVjLabel)
                .addGap(20, 20, 20))
        );

        TKjPanel5.setBackground(new java.awt.Color(180, 159, 220));

        TKjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TKjLabel.setText("Thống kê");

        javax.swing.GroupLayout TKjPanel5Layout = new javax.swing.GroupLayout(TKjPanel5);
        TKjPanel5.setLayout(TKjPanel5Layout);
        TKjPanel5Layout.setHorizontalGroup(
            TKjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TKjPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(TKjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TKjPanel5Layout.setVerticalGroup(
            TKjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TKjPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TKjLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        LTjPanel.setBackground(new java.awt.Color(180, 159, 220));

        TKjLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TKjLabel1.setText("Quản lý loại tour");

        javax.swing.GroupLayout LTjPanelLayout = new javax.swing.GroupLayout(LTjPanel);
        LTjPanel.setLayout(LTjPanelLayout);
        LTjPanelLayout.setHorizontalGroup(
            LTjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LTjPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(TKjLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LTjPanelLayout.setVerticalGroup(
            LTjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LTjPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(TKjLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPnConLayout = new javax.swing.GroupLayout(jPnCon);
        jPnCon.setLayout(jPnConLayout);
        jPnConLayout.setHorizontalGroup(
            jPnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPnConLayout.setVerticalGroup(
            jPnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );

        DDjPanel.setBackground(new java.awt.Color(180, 159, 220));

        DDjLabell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DDjLabell.setText("Quản lý địa điểm");

        javax.swing.GroupLayout DDjPanelLayout = new javax.swing.GroupLayout(DDjPanel);
        DDjPanel.setLayout(DDjPanelLayout);
        DDjPanelLayout.setHorizontalGroup(
            DDjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DDjPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(DDjLabell)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DDjPanelLayout.setVerticalGroup(
            DDjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DDjPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(DDjLabell)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tourjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GiajPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LTjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TKjPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NVjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KHjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CPPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DoanjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DDjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPnCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tourjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GiajPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(DoanjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(CPPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KHjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NVjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TKjPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LTjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DDjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPnCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btnDangXuat) {
            this.setVisible(false);
            new QLTOUR().setVisible(true);
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPLabel;
    private javax.swing.JPanel CPPanel;
    private javax.swing.JLabel DDjLabell;
    private javax.swing.JPanel DDjPanel;
    private javax.swing.JLabel DoanjLabel;
    private javax.swing.JPanel DoanjPanel;
    private javax.swing.JLabel GiajLabel;
    private javax.swing.JPanel GiajPanel;
    private javax.swing.JLabel KHjLabel;
    private javax.swing.JPanel KHjPanel;
    private javax.swing.JPanel LTjPanel;
    private javax.swing.JLabel NVjLabel;
    private javax.swing.JPanel NVjPanel;
    private javax.swing.JLabel TKjLabel;
    private javax.swing.JLabel TKjLabel1;
    private javax.swing.JPanel TKjPanel5;
    private javax.swing.JLabel TourjLabel;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnCon;
    private javax.swing.JPanel tourjPanel;
    // End of variables declaration//GEN-END:variables
}
